name: E2E Chrome Tests - Sharded

on:
  push:
    branches:
      - feat/**
      - test/**
  workflow_dispatch:

concurrency:
  group: e2e-chrome-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v1-deps-${{ hashFiles('yarn.lock') }}
      
      - run: yarn install
      
      - name: Build from NX Cloud cache
        run: (NX_VERBOSE_LOGGING=1 node --max-old-space-size=4096 ./node_modules/.bin/nx build --cloud --verbose)
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      
      - run: yarn inject-e2e-config
      
      - run: yarn run build:e2e
      
      - run: grep -ir "[0-9]+commit" apps/* libs/* --include \*.ts --include \*.tsx --include \*.json > soljson-versions.txt
      
      - name: Cache soljson assets
        uses: actions/cache@v4
        with:
          path: dist/apps/remix-ide/assets/js/soljson
          key: soljson-v7-${{ hashFiles('soljson-versions.txt') }}
      
      - run: yarn run downloadsolc_assets_e2e
      
      - name: Save soljson cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: dist/apps/remix-ide/assets/js/soljson
          key: soljson-v7-${{ hashFiles('soljson-versions.txt') }}
  
  remix-ide-chrome:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v1-deps-${{ hashFiles('yarn.lock') }}
      
      - run: yarn install
      
      - name: Build from NX Cloud cache
        run: yarn build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      
      - run: yarn inject-e2e-config
      
      - run: yarn run build:e2e
      
      - run: grep -ir "[0-9]+commit" apps/* libs/* --include \*.ts --include \*.tsx --include \*.json > soljson-versions.txt
      
      - name: Cache soljson assets
        uses: actions/cache@v4
        with:
          path: dist/apps/remix-ide/assets/js/soljson
          key: soljson-v7-${{ hashFiles('soljson-versions.txt') }}
      
      - run: yarn run downloadsolc_assets_e2e
      
      - run: |
          mkdir -p node_modules/hardhat
          wget https://unpkg.com/hardhat/console.sol -O node_modules/hardhat/console.sol
      
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Install ChromeDriver
        run: |
          yarn install_webdriver
          if [ -f "./tmp/webdrivers/chromedriver-linux64/chromedriver" ]; then
            mv ./tmp/webdrivers/chromedriver-linux64/chromedriver ./tmp/webdrivers/chromedriver
          fi
      
      - run: ./apps/remix-ide/ci/browser_test_github.sh chrome 20 ${{ matrix.job }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-chrome-${{ matrix.job }}
          path: reports/tests
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-chrome-${{ matrix.job }}
          path: reports/screenshots
