name: E2E Tests - Chrome (On Demand)

on:
  push:
    branches:
      - feat/nx-cloud/setup  # Temporary: just to register the workflow
  workflow_dispatch:
    inputs:
      test_pattern:
        description: 'Test file pattern (e.g., "**/*group1*.test.js" or leave empty for all)'
        required: false
        default: ''
        type: string

jobs:
  e2e-chrome:
    name: Run E2E Chrome Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build from NX Cloud cache
        run: yarn build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      
      - name: Inject E2E test configuration
        run: yarn inject-e2e-config
      
      - name: Build E2E tests
        run: yarn run build:e2e
      
      - name: Download Solidity compiler assets
        run: |
          grep -ir "[0-9]+commit" apps/* libs/* --include \*.ts --include \*.tsx --include \*.json > soljson-versions.txt
          yarn run downloadsolc_assets_e2e
      
      - name: Install system dependencies
        run: |
          mkdir -p node_modules/hardhat
          wget https://unpkg.com/hardhat/console.sol -O node_modules/hardhat/console.sol
      
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Install ChromeDriver
        run: yarn install_webdriver
      
      - name: Run Nightwatch E2E tests
        run: |
          if [ -n "${{ inputs.test_pattern }}" ]; then
            echo "Running tests matching pattern: ${{ inputs.test_pattern }}"
            yarn nightwatch --config dist/apps/remix-ide-e2e/nightwatch-chrome.js "${{ inputs.test_pattern }}" --env=chromeDesktop
          else
            echo "Running all E2E tests"
            yarn nightwatch --config dist/apps/remix-ide-e2e/nightwatch-chrome.js dist/apps/remix-ide-e2e/src/tests/**/*.test.js --env=chromeDesktop
          fi
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      
      - name: Upload test screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: reports/screenshots/
          retention-days: 7
      
      - name: Upload test reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports
          path: reports/tests/
          retention-days: 7
      
      - name: Test summary
        if: always()
        run: |
          if [ -f reports/tests/*.xml ]; then
            echo "📊 Test results available in artifacts"
          fi
          echo "✅ E2E tests completed"
